name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
      APP_NAME: gh-flow
      ENV: ""
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Release
        id: build_package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: ridedott/release-me-action@v3.5.53
        with:
          release-branches: '["main", "master"]'
          config-file: .releaserc.yml

      - uses: actions/setup-python@v2
        if: steps.build_package.outputs.released == 'true'

      - uses: aws-actions/setup-sam@v1
        if: steps.build_package.outputs.released == 'true'

      - name: Configure AWS credentials
        if: steps.build_package.outputs.released == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Build
        run: sam build --use-container
        if: steps.build_package.outputs.released == 'true'

      - name: Environment
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            environment="prod"
            echo "ENV=$(echo ${environment})" >> $GITHUB_ENV
          fi
      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ env.APP_NAME}} --s3-bucket ${{ env.AWS_S3_BUCKET}} --capabilities CAPABILITY_IAM --parameter-overrides ParameterKey=Environment,ParameterValue=${{ env.ENV}}

