name: CI/Python/Lint-Test

on:
  push:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TF_VAR_lambda: ""
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - name: Install Pylint 
        run:
          pip install pylint

      - name: Pylint 
        continue-on-error: true
        run:
          pylint src

  test:
    runs-on: ubuntu-latest
    env:
      TF_VAR_lambda: ""
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Install dependencies
        run:
          pip install pytest pytest-mock boto3 requests

      - name: Test 
        run:
          python -m pytest tests/ -v
        env:
          AWS_SAM_STACK_NAME: gh-flow
