name: CI/SAM/Validate

on:
  push:
    paths:
      - 'template.yaml'
jobs:
  tf-validate:
    runs-on: ubuntu-latest
    env:
      TF_VAR_lambda: ""
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-python@v2
        if: steps.build_package.outputs.released == 'true'

      - uses: aws-actions/setup-sam@v1
        if: steps.build_package.outputs.released == 'true'

      - name: Configure AWS credentials
        if: steps.build_package.outputs.released == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Validate
        run: sam validate
