name: CI/TF/Validate

on:
  push:
    paths:
      - '**.tf'
      - '**.hcl'
jobs:
  tf-validate:
    runs-on: ubuntu-latest
    env:
      TF_VAR_lambda: ""
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Terragrunt
        # if: steps.build_package.outputs.released == 'true'
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.34.0

      - name: Terragrunt Validate
        # if: steps.build_package.outputs.released == 'true'
        working-directory: ${{ env.TF_DIR }}
        run: terragrunt run-all validate
        env:
          TF_VAR_list_lambdas: '${{ env.TF_VAR_list_lambdas }}'
