name: CI/TF/Validate

on:
  push:
    paths:
      - '**.tf'
      - '**.hcl'
jobs:
  tf-validate:
    runs-on: ubuntu-latest
    env:
      TF_VAR_lambda: ""
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.34.0

      - name: Terragrunt Validate
        working-directory: ${{ env.TF_DIR }}
        run: terragrunt run-all validate
        env:
          TF_VAR_list_lambdas: '${{ env.TF_VAR_list_lambdas }}'
